version: '3'
services:
  realworld-db:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  realworld-api:
    image: realworld-spring-webflux:latest
    ports:
      - "8081:8080"
    environment:
      - "JAVA_TOOL_OPTIONS=-agentpath:/data/agent/libdrill_agent.so=drillApiUrl=${DRILL_API_URL},appId=spring-webflux,groupId=realworld,drillApiKey=${DRILL_API_KEY},packagePrefixes=com/realworld,logLevel=INFO,commitSha=${GITHUB_SHA}"
      - "SPRING_DATA_MONGODB_HOST=realworld-db"
      - "SPRING_DATA_MONGODB_PORT=27017"
      - "SPRING_DATA_MONGODB_DATABASE=realworld-db"
      - "SPRING_DATA_MONGODB_USERNAME=root"
      - "SPRING_DATA_MONGODB_PASSWORD=example"
    depends_on:
      - realworld-db
    volumes:
      - ./agent/linuxX64-0.9.0-beta.3/:/data/agent
