name: Workflow for mac-os arm64 with autotest-agent
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened, reopened, synchronize ]

env:
  BASE_URL: ${{ vars.REALWORLD_API_URL }}
  DRILL_API_KEY: ${{ secrets.DRILL_API_KEY }}
  DRILL_API_URL: ${{ vars.DRILL_API_URL }}
  DRILL_BOT_GITHUB_TOKEN: ${{ secrets.DRILL_BOT_GITHUB_TOKEN }}
  DRILL_AUTOTEST_AGENT_URL: ${{ vars.DRILL_AUTOTEST_AGENT_URL }}
jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Validate Gradle
        uses: gradle/actions/wrapper-validation@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run api tests
        run: ./gradlew runApiTests