name: Demo workflow
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, synchronize]

env:
  BASE_URL: http://0.0.0.0:8081
  DRILL_API_KEY: ${{ secrets.DRILL_API_KEY }}
  DRILL_API_URL: ${{ vars.DRILL_API_URL }}
  DRILL_BOT_GITHUB_TOKEN: ${{ secrets.DRILL_BOT_GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Validate Gradle
        uses: gradle/actions/wrapper-validation@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build app
        run: ./gradlew clean assemble
      - name: Build and export api-test
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile-api-tests
          context: .
          tags: api-tests:latest
          outputs: type=docker,dest=/tmp/api-tests.tar
      - name: Build and export backend
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile-api-backend
          context: .
          tags: realworld-spring-webflux:latest
          outputs: type=docker,dest=/tmp/api-backend.tar
      - name: Send build info to Drill4J
        run: ./gradlew drillSendBuildInfo
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: realworld-images
          path: /tmp/*.tar
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: realworld-images
          path: /tmp
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Load backend image
        run: docker load --input /tmp/api-backend.tar
      - name: Load api-tests image
        run: docker load --input /tmp/api-tests.tar
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Download java-agent
        run: curl -L ${{ vars.JAVA_AGENT_URL }} -o agent.zip
      - name: Unzip java-agent
        run: unzip agent.zip -d Docker/agent/
      - name: Run docker-compose
        run: docker compose -f ./Docker/docker-compose.yml up --exit-code-from api-tests
        env:
          DRILL_COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
  reportByPR:
    if: github.event_name == 'pull_request'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Validate Gradle
        uses: gradle/actions/wrapper-validation@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Send coverage report to Drill4J
        run: ./gradlew drillGithubPullRequestReport
  reportByBranch:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate Gradle
        uses: gradle/actions/wrapper-validation@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Generate Drill4J Change Testing Report
        run: ./gradlew drillGenerateChangeTestingReport
      - name: Archive report
        uses: actions/upload-artifact@v4
        with:
          name: change-testing-report
          path: drillReport.md