name: Demo workflow
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request_target:
    types: [opened, reopened, synchronize]


env:
  BASE_URL: http://0.0.0.0:8081
  DRILL_API_KEY: ${{ secrets.DRILL_API_KEY }}
  DRILL_API_URL: ${{ vars.DRILL_API_URL }}
  DRILL_BOT_GITHUB_TOKEN: ${{ secrets.DRILL_BOT_GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Validate Gradle
        uses: gradle/actions/wrapper-validation@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build app
        run: ./gradlew clean assemble
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: realworld-spring-webflux:latest
          outputs: type=docker,dest=/tmp/app.tar
      - name: Send build info to Drill
        run: ./gradlew drillSendBuildInfo
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: realworld-image
          path: /tmp/app.tar
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: realworld-image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/app.tar
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download java-agent
        run: curl -L ${{ vars.JAVA_AGENT_URL }} -o agent.zip
      - name: Unzip java-agent
        run: unzip agent.zip -d Docker/agent/
      - name: Run docker-compose
        run: docker-compose -f ./Docker/docker-compose.yml up -d
      - name: Validate Gradle
        uses: gradle/actions/wrapper-validation@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run api tests
        run: ./gradlew runApiTests
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Docker-compose down
        run: docker-compose -f ./Docker/docker-compose.yml down -v
  report:
    if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle
        uses: gradle/actions/wrapper-validation@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Send coverage report from Drill
        run: ./gradlew drillGithubPullRequestReport