name: Demo workflow unit tests
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened, reopened, synchronize ]

env:
  DRILL_API_KEY: ${{ secrets.DRILL_API_KEY }}
  DRILL_API_URL: ${{ vars.DRILL_API_URL }}
  DRILL_COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Validate Gradle
        uses: gradle/actions/wrapper-validation@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run unit tests
        run: ./gradlew test
